# Generated by Django 3.1.1 on 2020-09-15 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang_source', models.CharField(max_length=15, verbose_name='language source')),
                ('lang_target', models.CharField(max_length=15, verbose_name='language target')),
                ('text', models.TextField(verbose_name='text')),
                ('traslation', models.TextField(null=True, verbose_name='traslation')),
                ('status', models.SmallIntegerField(choices=[(1, 'REQUESTED'), (2, 'TRASLATED'), (3, 'FAILED')], default=1, editable=False, verbose_name='status')),
                ('creation_time', models.DateTimeField(auto_now=True, verbose_name='creation time')),
                ('finish_time', models.DateTimeField(editable=False, null=True, verbose_name='finish time')),
            ],
            options={
                'verbose_name': 'traslation',
                'verbose_name_plural': 'traslations',
            },
        ),
    ]
